Pipelines/Scripts/repackage-for-release.ps1

The regex for extracting the version number from the package.json file was grabbing the wrong version in some instances.  Fixed.

Fix regex in repackaging script

---

Pipelines/Scripts/repackage-for-release.ps1

The regex for extracting the version number from the package.json file was grabbing the wrong version in some instances.  Fixed.
(cherry picked from commit 20a0728a751736b928f58fc0493c613e26839e05)

Fix regex in repackaging script (#427)

---

Pipelines/Scripts/repackage-for-release.ps1
org.mixedrealitytoolkit.core/Editor/PropertyDrawers/ExperimentalDrawer.cs

Fix ExperimentalDrawer.cs doesn't compile in Unity Editor 2022.3.2f1 and above. https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/40
Use a cached height calculated in OnGUI().

Fix issue #40: ExperimentalDrawer.cs doesn't compile in Unity Editor 2022.3.2f1 

---

org.mixedrealitytoolkit.core/Editor/PropertyDrawers/ExperimentalDrawer.cs

* Fix ExperimentalDrawer.cs doesn't compile in Unity Editor 2022.3.2f1 and above. #40 Use a cached height calculated in OnGUI().
(cherry picked from commit 770b1c41cb32479cd3a223023efd4fabb5b530a4)

Cherry pick #430 to release/3.0.0

---

org.mixedrealitytoolkit.uxcore/Slider/SliderSounds.cs

This change serializes the grabReleaseAudioSource and passNotchAudioSource AudioSource fields, so that developer customers can configure options such as AudioMixerGroup, spatialization and play on awake.
Fixes: #435 
Verified in Unity editor by:
- Adding a single AudioSource to the slider in the HandInteractionExamplesScene
- Assigning the manually attached AudioSource to the Grab/Release and PassNotch fields (newly serialized)
- Playing the scene in the editor and moving the slider
- Noting
- No additional AudioSource objects were added to the slider
- Audio plays correctly
- The expected AudioSource parameters are updated while interacting with the slider

Enable developer customers to access AudioSource at development time

---

org.mixedrealitytoolkit.standardassets/Icons/LICENSE.md
org.mixedrealitytoolkit.standardassets/Icons/LICENSE.md.meta

The fluent icon set is licensed under the MIT license by Microsoft.  Adding that sub license to the icon directory.
Reference https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity-Maintainers/issues/9

Fluent icon set license

---

org.mixedrealitytoolkit.standardassets/Icons/LICENSE.md
org.mixedrealitytoolkit.standardassets/Icons/LICENSE.md.meta

The fluent icon set is licensed under the MIT license by Microsoft.  Adding that sub license to the icon directory.
(cherry picked from commit a75cbe1cd2d0643896ed0659620d95aa06bb720e)

Cherry pick: Fluent icon set license (#443)

---

Pipelines/Scripts/publish-upm.ps1
contributions/versioning-and-releases.md

Updating publish upm script to better handle out-of-date tokens.  Also, updating steps for releasing new packages, to clarify branch naming, verififcation, and preview releases.
Adding the `-force` flag to the publishing script will help in cases where the cached verification token as expired.
Also, the release steps weren't clear on how to create a `release` branch and how to handle preview packages.  Also, I'm explicitly calling out releases should be on per package basis, to avoid multi-package releases in the future (i.e. post-GA).  And clarifying that the release process includes verifying that the package version is correct, and that dependent packages work with the new version.

Updating publish upm script to better handle out-of-date tokens

---

DEPENDS.md
README.md

This page catalogs the project's externals dependencies and the reason for requiring a particular dependency version. If an external dependency is added or a dependency version is updated, this page must be updated.
All dependency entries must specify a minimum supported version. If a maximum version is known, it too must be specified. If the maximum version is blank, then there is no known maximum version and versions after the minimum version may work with MRTK. A blank maximum version does not guarantee that all versions after the minimum will function properly.
When updating a dependency version, add a new row to the top of the dependency's history table. The change's date, author, and reason must be specified in the added row.
- Fixes: …

Adding a markdown file to track dependencies versions.

---

org.mixedrealitytoolkit.core/MRTK.Core.asmdef
org.mixedrealitytoolkit.core/Utilities/ComponentCache.cs
org.mixedrealitytoolkit.core/Utilities/ControllerLookup.cs
org.mixedrealitytoolkit.uxcore/Tests/Runtime/SeeItSayItLabelEnablerTests.cs

Adds ifdefs to allow < Unity 2021.3.18 to compile. 
Unity 2021.3.18 introduced several more efficient functions: Object.FindObjectsByType(), Object.FindFirstObjectByType(), Object.FindAnyObjectByType(). This PR adds back the ability to use the older versions of these calls if version < 2021.3.18. 
Resolves https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/467.

Add Precompile Statements to Avoid Errors in < Unity 2021.3.18

---

UnityProjects/.gitignore

Allows devs to import samples for testing without polluting their git changes. This is a Unity-generated folder when samples are imported via UPM.

Add Samples folder to .gitignore

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
org.mixedrealitytoolkit.core/Utilities/HandsUtils.cs
org.mixedrealitytoolkit.core/Utilities/TrackedHandJoint.cs
org.mixedrealitytoolkit.core/Utilities/XRSubsystemHelpers.cs
org.mixedrealitytoolkit.core/package.json
org.mixedrealitytoolkit.input/Subsystems/Hands/HandsProvider.cs
org.mixedrealitytoolkit.input/Subsystems/Hands/HandsProvider.cs.meta
org.mixedrealitytoolkit.input/Subsystems/Hands/OpenXRHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/Hands/XRSDKHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/HandsAggregator/MRTKHandsAggregatorSubsystem.cs
org.mixedrealitytoolkit.input/package.json

First step of https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/66, to reduce the boilerplate code needed to spin up a new hands provider.
Also refactors out `DefaultHandJointRadius`, as `0.005f` was used in a couple places.
Also, some assorted formatting and slight perf updates.

Refactor out HandsProvider<T>

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
org.mixedrealitytoolkit.uxcomponents.noncanvas/Slider/NonCanvasSliderBase.prefab
org.mixedrealitytoolkit.uxcomponents.noncanvas/package.json
org.mixedrealitytoolkit.uxcomponents/Slider/CanvasSlider.prefab
org.mixedrealitytoolkit.uxcomponents/package.json
org.mixedrealitytoolkit.uxcore/Slider/SliderSounds.cs

* unify slider audio sources, cache and restore the pitch shift value
* update package versionsto match slidersounds and prefab updates
* reserialize packages-lock with 2021.3.21f1
* remodify/serialize prefabs with 2021.3.21f1
* Update org.mixedrealitytoolkit.uxcore/Slider/SliderSounds.cs
* pr feedback: code improvements
---------

Update SliderSounds to use one AudioSource instead of two (#495)

---

org.mixedrealitytoolkit.input/Tracking/UnboundedTrackingMode.cs

This file has a namespace that wasn't being used, and not present on iOS and other non-MRPlugin platforms.
Fixes:
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/514

Fixing build error impacting non-MRPlugin Platforms: Removing unneeded namespace

---

UnityProjects/MRTKDevTemplate/Assets/Scripts/SampleSceneHandMenu.cs
org.mixedrealitytoolkit.core/Tests/Runtime/InteractableEventRouterTests.cs
org.mixedrealitytoolkit.core/Utilities/ComponentCache.cs
org.mixedrealitytoolkit.core/Utilities/ControllerLookup.cs
org.mixedrealitytoolkit.core/Utilities/FindObjectUtility.cs
org.mixedrealitytoolkit.core/Utilities/FindObjectUtility.cs.meta
org.mixedrealitytoolkit.core/package.json
org.mixedrealitytoolkit.input/Editor/InputValidation.cs
org.mixedrealitytoolkit.input/InteractionModes/InteractionModeManager.cs
org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTests.cs
org.mixedrealitytoolkit.input/Tests/Runtime/FuzzyGazeInteractorTests.cs
org.mixedrealitytoolkit.input/Tests/Runtime/InteractionModeManagerTests.cs
org.mixedrealitytoolkit.input/Tests/Runtime/Utilities/BaseRuntimeInputTests.cs
org.mixedrealitytoolkit.input/Tests/Runtime/Utilities/InputTestUtilities.cs
org.mixedrealitytoolkit.input/package.json
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/BoundsControlTests.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverHandlerTests.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTests.cs
org.mixedrealitytoolkit.spatialmanipulation/package.json
org.mixedrealitytoolkit.uxcomponents.noncanvas/Tests/Runtime/DialogTests.cs
org.mixedrealitytoolkit.uxcomponents.noncanvas/package.json
org.mixedrealitytoolkit.uxcomponents/Tests/Runtime/CanvasDialogTests.cs
org.mixedrealitytoolkit.uxcomponents/package.json
org.mixedrealitytoolkit.uxcore/Tests/Runtime/SeeItSayItLabelEnablerTests.cs
org.mixedrealitytoolkit.uxcore/package.json

Following @keveleigh's suggestion to refactor this PR https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/506.
FIxes:
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/502

Add Precompile Statements to Prevent Warnings in Unity 2023 (Refactored)

---

DEPENDS.md
UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
org.mixedrealitytoolkit.input/MRTK.Input.asmdef
org.mixedrealitytoolkit.input/Subsystems/Hands/OpenXRHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/Hands/UnityHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/Hands/UnityHandsSubsystem.cs.meta
org.mixedrealitytoolkit.input/Subsystems/Hands/XRSDKHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs
org.mixedrealitytoolkit.input/package.json

Next phase of #66: actually creating the hands provider wrapping Unity's XR Hands API.
1. Creates the `HandsSubsystem` implementation wrapping Unity's XR Hands API.
2. As a result, adds Unity's XR Hands package as a hard dependency to the Input package.
3. DOES NOT yet change any MRTK profiles or sample scenes. That will come in the next PR.
Does not complete https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/66 but is a major step along to completion.

Unity XR Hands provider

---

UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

These match the Project Name and Organization Name elsewhere in the serialization. They only update on build, I believe, so it just wasn't updated when the previous updates were made.

Update serialized applicationIdentifiers

---

org.mixedrealitytoolkit.uxcore/Experimental/List/VirtualizedScrollRectList.cs
org.mixedrealitytoolkit.uxcore/package.json

Add fix for #534 
When using the VirtualizedScrollRectList, the pool item prefabs are spawned as children of scrollRect.content with an initial rotation of Quaternion.identity. If the ScollRect or content are rotated, this will spawn the pool items at an angle to the ScrollRect whereas the desired behaviour is probably to spawn them aligned.
This fix instantiates the list items with the parent's rotation.

Fix improper list item rotation in VirtualizedScrollRectList (#534)

---

org.mixedrealitytoolkit.uxcomponents/Slider/CanvasSlider.prefab
org.mixedrealitytoolkit.uxcore/Slider/Slider.cs
org.mixedrealitytoolkit.uxcore/Slider/Visuals/CanvasSliderVisuals.cs

Implement fixes related to setting the slider value programmatically: canvas slider handle calculations now use canvas positioning, aligning with fillVisual. Issue and workaround reported by @anonymous2585, https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/523.
Also adds a check to limit Slider value within the range of min and max values, removes arbitrary prefab value.

Fix Canvas Slider Handle Positioning and Impose MinMax Limits to Slider Value

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/DisableInteractorsExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat.meta
org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedPurple.mat
org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedPurple.mat.meta
org.mixedrealitytoolkit.extendedassets/package.json

Fixes: #544 
Fixes a minor cosmetic / quality issue with some of the MRTKDevTemplate samples where some of the colored cubes change color once grabbed and released.  The intended behavior would be for the cubes to retain their color to maintain the uniqueness of each cube during and after manipulation, even after falling off the edge and being restored.
Just a minor issue with a simple material reference fix.

Fix minor issue of cubes changing color in some scenes when grabbed

---

org.mixedrealitytoolkit.spatialmanipulation/Editor/ObjectManipulator/ObjectManipulatorEditor.cs
org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/ObjectManipulator.cs
org.mixedrealitytoolkit.spatialmanipulation/package.json

This adds XRI's XRBaseInteractable.MovementType to ObjectManipulator so devs can specify the movement type of the rigid body during manipulation.
Currently the behavior always forces non-kinematic "Velocity Tracking" when a rigid body is attached, setting velocity and angular velocity to move the rigid body.  This would allow the dev to specify other types of movement, like kinematic, as is provided in XRI.  This also observes the XRBaseInteractor.selectedInteractableMovementTypeOverride when an interactor overrides the movement type.
Resolves:  #532 
Related to being more compatible with XRI #67

Adding Rigidbody MovementType to ObjectManipulator

---

org.mixedrealitytoolkit.input/Visualizers/ControllerVisualizer/Models/generic-trigger-squeeze-touchpad-thumbstick/LeftControllerModel.prefab
org.mixedrealitytoolkit.input/Visualizers/ControllerVisualizer/Models/generic-trigger-squeeze-touchpad-thumbstick/RightControllerModel.prefab
org.mixedrealitytoolkit.input/Visualizers/RiggedHandVisualizer/openxr_left_hand.prefab
org.mixedrealitytoolkit.input/Visualizers/RiggedHandVisualizer/openxr_right_hand.prefab

Fixes https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/241, specifically:
> I think the problem was a wrong version of glTFast in the project.
It looks like we were hitting a bit of a quirk with the Unity serialization system causing our fallback controller models to lose their reference when different glTFast versions were used compared to our sample scene.
As best as I can tell, the underlying problem is that our prefabs were direct variants of the imported glTF models. Unfortunately, it appears that the imported glTF models don't keep a consistent fileID across glTF importer versions. This caused the reference to the controller model prefabs to be lost in the hand prefabs when different glTF importer versions were used.
This PR updates our prefabs to _no longer_ …

Fix controller model fallback serialization

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/BoundsControl/ScaledBoundingBoxWithTraditionalHandles.prefab
UnityProjects/MRTKDevTemplate/Assets/Prefabs/BoundsControl/ScaledBoundingBoxWithTraditionalHandles.prefab.meta
UnityProjects/MRTKDevTemplate/Assets/Scenes/BoundsControlRuntimeExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scripts/BoundsControlRuntimeExample.cs
org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsHandleInteractable.cs
org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/Prefabs/BoundingBoxWithHandles.prefab
org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/Prefabs/BoundingBoxWithTraditionalHandles.prefab

Currently, all BoundsHandleInteractables are set to a global scale of 1x1x1 at runtime (and may then scale with the bounding box if MaintainGlobalSize is unselected). The initial scale of BoundsHandleInteractable is never taken into account when scaling the handles. This change sets the global scale to the max(x,y,z) of the initial BoundsHandleInteractable scale, instead of 1, so a user may now change the size of the handles in the prefab in order to make bounding boxes with larger or smaller handles. PR also makes changes to the BoundsControlRuntimeExample scene to give an example of this.
[3x3x3 Handles Scaled Prefab from Sample Scene]
Addresses https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/572
Spatial Manipulation package version number has already been bumped …

Allow Variable Bounding Box Handle Sizes

---

org.mixedrealitytoolkit.input/Interactors/Speech/SpeechInteractor.cs

Fix #612 
If user or code set the SpeechRecognitionKeyword to an empty or whitespace string, the SpeechInteractor won't register the blank keyword in the keywordDictionary and won't transmit it to the subsystem.

Fix empty SpeechRecognitionKeyword breaking all speech keyword system (#612)

---

GOVERNANCE.md

Updating maintainer rules, so that a maintainer's affiliated organization doesn't need representation on the steering committee.
Existing maintainers should approve this change.
Note, changes to these rules were already approved by the MRTK Steering Committee.

Updating maintainer rules

---

org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/MoveLogics/ManipulationLogic.cs
org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/MoveLogics/RotateLogic.cs
org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/MoveLogics/UnifiedMoveLogic.cs
org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/ObjectManipulator.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/ObjectManipulatorTests.cs

* Modifies ManipulationLogic for position and rotation to properly observe XRSocketInteractor.
* Turns off object smoothing when selected by XRSocketInteractor.
* Also observes XRRayInteractor forceGrab property for position, moving the object to the ray interactor's force grab attach transform.
Resolves #492

ObjectManipulator's ManipulationLogic observes XRSocketInteractor

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
org.mixedrealitytoolkit.core/Utilities/StabilizedRay.cs
org.mixedrealitytoolkit.core/package.json
org.mixedrealitytoolkit.input/Utilities/PoseSource/LOSAngularOffsetHandRayPoseSource.cs
org.mixedrealitytoolkit.input/Utilities/PoseSource/LOSAngularOffsetHandRayPoseSource.cs.meta
org.mixedrealitytoolkit.input/Utilities/PoseSource/PolyfillHandRayPoseSource.cs
org.mixedrealitytoolkit.input/package.json

Fixes #548 
Likely also fixes #580 
Fixes the issue by adding an alternative hand ray pose source that can optionally be used that is much less affected by head rotations.  To utilize the new hand ray pose source, within the MRTK XR Rig, select the Far Ray of each hand:
Then in the Inspector for each Far Ray, add an Aim Pose Source and select the LOSAngularOffsetHandRayPoseSource.  Move the new pose source to the top of the list so it takes precedence, and set the hand:
Example video demonstrating the change.  The white ray is the existing hand ray, the green ray is the new LOSAngularOffsetHandRayPoseSource:
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/58860572/38b95fe7-1bfb-4d75-87ea-443d8e2ced91

Add alternative LOSAngularOffsetHandRayPoseSource

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
org.mixedrealitytoolkit.uxcomponents/Button/Prefabs/Empty Button.prefab
org.mixedrealitytoolkit.uxcomponents/Tests/Runtime/ScrollableTests.cs
org.mixedrealitytoolkit.uxcomponents/package.json
org.mixedrealitytoolkit.uxcore/Button/RectTransformColliderFitter.cs
org.mixedrealitytoolkit.uxcore/Button/StatefulInteractableColliderToggle.cs
org.mixedrealitytoolkit.uxcore/Button/StatefulInteractableColliderToggle.cs.meta
org.mixedrealitytoolkit.uxcore/package.json

This pull request aims to make it easier to disable an interactable’s colliders when `StatefiulInteractable.IsInteractable` is false or when the `StatefiulInteractable.enabled` is false. This is because list scrolling would break if the user attempted to scroll the list while focusing the disabled interactable. This is because the interactable’s collider was still enabled and blocking ray casts to the list’s backplate.
To work around this, this change adds a new button component, `StatefulInteractableColliderToggle`, and new property, `RectTransformColliderFitter.CanToggleCollider`. The new `RectTransformColliderFitter` property, `CanToggleCollider`, will allow code to turn off the fitter’s automatic enabling/disabling when the collider's visibility changes. The new behavior class, …

Auto disable button's colliders when `StatefulInteractable` is disabled

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Experimental/CanvasExampleSimpleActionButton.unity
org.mixedrealitytoolkit.uxcomponents.noncanvas/Tests/Runtime/PressableButtonTests.cs
org.mixedrealitytoolkit.uxcomponents/Button/Prefabs/Experimental/SimpleEmptyButton.prefab
org.mixedrealitytoolkit.uxcomponents/CHANGELOG.md
org.mixedrealitytoolkit.uxcomponents/package.json

Associated issue: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/643

Bug643-Fix adding missing SeeItSayItLabel, reference corresponding GameObject, and regression-prevention UnityTests

---

org.mixedrealitytoolkit.uxcore/Experimental/NonNativeKeyboard/KeyboardAudio.cs

The NonNativeKeyboard consists out of several panes. the keyboard_Alpha and keyboard_Space_Alpha are active. However, if you press the &123 button, the keyboard_Symbols gets active. The buttons on this pane do not make sound, because it uses `GetComponentsInChildren<Button>()` to find the button, which only finds active game objects, while it should use `GetComponentsInChildren<Button>(true)`, which finds both active _and_ inactive game objects

Fixes buttons of secondary keyboard layouts not making any sound

---

org.mixedrealitytoolkit.uxcore/Interop/CanvasProxyInteractor.cs

* Fixes: #669
* Modifies CanvasProxyInteractor to check if an Interactable is hoverable or selectable by it before proceeding with hover and select. This makes use of any hover and select filtering added to the Interactable.

Fix issue with CanvasProxyInteractor not observing hover & select filters

---

Pipelines/Config/settings.yaml
UnityProjects/MRTKDevTemplate/Assets/Data Binding Example/Resources/Fonts & Materials/CooperHewitt-BoldItalic SDF.asset
org.mixedrealitytoolkit.standardassets/Icons/MRTK_FluentIconSet SDF.asset

Updating MRTK_FluentIconSet SDF's shader to a Graphic Tools TMPro shader, so the font works in UPM projects.
Also, setting the Data packages's CooperHewitt-BoldItalic SDK shader to the Graphic Tools TMPro shader, is its original shader is missing.
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/668
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/672

Fixing shaders of a couple of TMPro fonts

---

org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/Controllers/ArticulatedHandController.cs
org.mixedrealitytoolkit.input/package.json

This could show up on runtimes where a controller is disconnected, hand tracking spins up, but the interaction profile is not cleared. This is allowed, per-spec: "The runtime may return the last-known interaction profile in the event that no controllers are active."
If we have a bound but untracked interaction profile, we now make an attempt at polyfilling based on hand tracking data.
Fixes #703

Add logic to account for a bound but untracked interaction profile

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/OutlineExamples.unity

Fixes #692
The XRI hover events on the center of the tripod object in the OutlineExample scene were not set, resulting in the outline not appearing when selecting, looking at or pointing at the object.

Assigned XRI hover events for tripod center piece to enable outlines (Fixes #692)

---

UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
org.mixedrealitytoolkit.accessibility/CHANGELOG.md
org.mixedrealitytoolkit.accessibility/package.json
org.mixedrealitytoolkit.audio/CHANGELOG.md
org.mixedrealitytoolkit.audio/Tests/Editor/MRTK.Audio.EditorTests.asmdef
org.mixedrealitytoolkit.audio/package.json
org.mixedrealitytoolkit.data/CHANGELOG.md
org.mixedrealitytoolkit.data/package.json
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/package.json
org.mixedrealitytoolkit.tools/CHANGELOG.md
org.mixedrealitytoolkit.tools/Tests/Editor/MRTK.Tools.EditorTests.asmdef
org.mixedrealitytoolkit.tools/package.json
org.mixedrealitytoolkit.uxcomponents.noncanvas/CHANGELOG.md
org.mixedrealitytoolkit.uxcomponents.noncanvas/package.json
org.mixedrealitytoolkit.uxcomponents/CHANGELOG.md
org.mixedrealitytoolkit.uxcomponents/package.json
org.mixedrealitytoolkit.uxcore/CHANGELOG.md
org.mixedrealitytoolkit.uxcore/package.json
org.mixedrealitytoolkit.windowsspeech/CHANGELOG.md
org.mixedrealitytoolkit.windowsspeech/package.json

The set of packages edited here had descriptions that were too long to meet Unity's requirements for publishing to Unity's UPM Asset Store.  The max character length is 200 characters.
I'm also updating the test project "validation" package to v0.5.1, which is the min validations package required when publishing to the asset store. Version 0.5.1 tests the 200 character limit.  So our unit tests should now catch this failure.
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/723

Fixing package descriptions so they are 200 characters or less, so packages can meet Unity's UPM Store Guidelines.

---

org.mixedrealitytoolkit.core/Utilities/Extensions/InteractorHandednessExtensions.cs
org.mixedrealitytoolkit.input/Assets/Prefabs/Experimental-XRI3/MRTK LeftHand Controller.prefab
org.mixedrealitytoolkit.input/Interactors/Ray/MRTKRayInteractor.cs

Aiming for the goal of removing *Controller* references in Interactors in this PR:
* Upgraded MRTKRayInteractor to handle the new components that replace pre-XRI3 components in experimental prefabs.
* Adjusted logic to have backward compatibility to support pre-XRI3 components.
Updated experimental prefabs so that the new TrackedPoseDriver field is linked to the parental MRTK*Hand prefab's TrackedPoseDriver as in:

XRI3 migration step05

---

org.mixedrealitytoolkit.input/Assets/Prefabs/Experimental-XRI3/MRTK LeftHand Controller.prefab
org.mixedrealitytoolkit.input/Interactors/Poke/PokeInteractor.cs

Aiming for the goal of removing *Controller* references in Interactors for XRI3 migration in this PR:
* Upgraded PokeInteractor::TryGetPokeRadius()
* Upgraded PokeInteractor.Handedness
* Upgraded PokeInteractor.isHoverActive
* Added a TrackedPoseDriver field
* Added a reference to the PokeInteractor's parent TrackedPoseDriver to the new TrackedPoseDriver field in the experimental *Hand Controler prefab, the experimental prefab now looks like this:
Manual testing done:
* Sideloaded a build with experimental prefabs on HL2, tested core scenes; all functionality works as expected, no broken assets detected.

XRI3 migration step 06

---

org.mixedrealitytoolkit.input/Assets/Prefabs/Experimental-XRI3/MRTK LeftHand Controller.prefab
org.mixedrealitytoolkit.input/Interactors/GazePinch/GazePinchInteractor.cs

Aiming for the goal of removing *Controller* references in Interactors for XRI3 migration in this PR:
* Upgraded GazePinchInteractor.Handedness
* Upgraded GazePinchInteractor.SelectProgress
* Updated comments
* Upgraded GazePinchInteractor.IsTracked
* Added TrackedPoseDriver field + linked to parent's TrackedPoseDriver in experimental prefab.  The prefab now looks like this:
Manual testing done:
* Sideloaded a build with experimental prefabs on HL2, tested core scenes; all functionality works as expected, no broken assets detected.

XRI3 migration step07

---

org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/MRTK.SpatialManipulation.RuntimeTests.asmdef
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverHandlerTests.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverHandlerTestsForControllerlessRig.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverHandlerTestsForControllerlessRig.cs.meta

* Added XRI3+ versions of SolverHandlerTests SolverHandlerInteractorLeftHandOnly, SolverHandlerInteractorMovesWithHand, SolverHandlerInteractorPreferredHandedness, SolverHandlerInteractorRightHandOnly, SolverHandlerInteractorSwitchesToActiveHand, SolverHandlerInteractorSwitchesToActiveHandWithEverythingValue, and SolverHandlerInteractorTracksInitialActiveHand.

XRI3 migration step10

---

org.mixedrealitytoolkit.spatialmanipulation/Solvers/TapToPlace.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTests.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTestsForControllerlessRig.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTestsForControllerlessRig.cs.meta

In this PR:
* Upgraded TapToPlace::RegisterPlacementAction() and TapToPlace::UnregisterPlacementAction() logic to handle both deprecated XRController selectActions and new XRI3+ Interactor's selectInput actions.
* Added XRI3+ versions of SolverTapToPlaceTests TapToPlaceFollowsRightHandRay and TapToPlaceFollowsLeftHandRay.

XRI3 migration step11

---

org.mixedrealitytoolkit.input/Tests/Runtime/MRTKRayInteractorVisualsTestsForControllerlessRig.cs
org.mixedrealitytoolkit.input/Tests/Runtime/MRTKRayInteractorVisualsTestsForControllerlessRig.cs.meta

In this PR:
* Added XRI3+ versions of MRTKRayInteractorVisualsTests ReticleAndLineVisualActiveTest.

XRI3 migration step12

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/ObsoleteHandInteractionExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/ObsoleteHandInteractionExamples.unity.meta
UnityProjects/MRTKDevTemplate/ProjectSettings/EditorBuildSettings.asset

For the goal of having a way to test the (soon to be) deprecated pre-XRI3 rig, in this PR:
* Made a copy of the existing HandInteractionExample and named it ObsoleteHandInteractionExample
* Updated scene description panel, it now looks like this:
* Added ObsoleteHandInteractionExample scene to default build settings.

XRI3 migration step15

---

org.mixedrealitytoolkit.core/CHANGELOG.md
org.mixedrealitytoolkit.core/Tests/TestUtilities/PackageValidatorResults.cs
org.mixedrealitytoolkit.core/package.json

After some of our packages were published to the Unity Asset Store, different error messages started to appear in our test suite. Ignore this message that's caused because the test runner is not part of our Publisher Account.
> Failed - "Asset Store Publisher"
Error: There is no publisher linked to this account. Read more about this error and potential solutions at https://docs.unity3d.com/Packages/com.unity.asset-store-validation@latest/index.html?preview=1&subfolder=/manual/asset_store_publisher_validation.html#there_is_no_publisher_linked_to_this_account

Ignore "Asset Store Publisher" test failures

---

org.mixedrealitytoolkit.input/Tests/Runtime/SpatialMouseInputTestsForControllerlessRig.cs
org.mixedrealitytoolkit.input/Tests/Runtime/SpatialMouseInputTestsForControllerlessRig.cs.meta

Adding SpatialMouseInteractorControllerlessSmokeTest Unity-test that verifies the experimental SpatialMouse controller has the correct (XRI3+) components and that its input actions are properly set.

Adding SpatialMouseInteractorControllerlessSmokeTest Unity-test

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
org.mixedrealitytoolkit.core/CHANGELOG.md
org.mixedrealitytoolkit.core/package.json
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/package.json
org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md
org.mixedrealitytoolkit.spatialmanipulation/package.json
org.mixedrealitytoolkit.uxcomponents.noncanvas/CHANGELOG.md
org.mixedrealitytoolkit.uxcomponents.noncanvas/package.json
org.mixedrealitytoolkit.uxcomponents/CHANGELOG.md
org.mixedrealitytoolkit.uxcomponents/package.json
org.mixedrealitytoolkit.uxcore/CHANGELOG.md
org.mixedrealitytoolkit.uxcore/package.json

* Updating modified packages to 4.0.0-development.pre.1 version
* Updating changelogs
* Bumping com.unity.xr.interaction.toolkit version 3.0.3
Additional manual testing:
* Quick test of all MRTK3 scenes with a sideloaded build on HL2:
* No core functionality impairment detected.
* No broken assets detected.

XRI3 migration readying [4.0.0-development.pre.1] packages

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Experimental/SpatialMouseSample.unity
org.mixedrealitytoolkit.input/Experimental/SpatialMouse/MRTK Spatial Mouse Controller.prefab

* Adding missing input action references in MRTK Spatial Mouse prefab.  The prefab now looks like this:
* Updating Spatial Mouse sample scene so that it uses the updated MRTK Spatial Mouse prefab.

XRI3 migration: adding missing spatial mouse action references

---

org.mixedrealitytoolkit.core/Tests/TestUtilities/BaseRuntimeTests.cs
org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md
org.mixedrealitytoolkit.spatialmanipulation/Solvers/TapToPlace.cs
org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTests.cs
org.mixedrealitytoolkit.spatialmanipulation/package.json

Fixes #784 
Added non-regression test.
Also corrected comments in tests.

Fix TapToPlace not starting when called before its Start (#784)

---

org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/Simulation/InputSimulator.cs

* Fix for InputSimulator not executing before InteractionManager
* Updated changelog.md accordingly

Fix for InputSimulator not executing before InteractionManager (#794)

---

org.mixedrealitytoolkit.input/MRTK.Input.asmdef
org.mixedrealitytoolkit.input/Tracking/TrackedPoseDriverWithFallback.cs

Refining the `TrackedPoseDriverWithFallback` implementation.
- Removing the need for `TDPwithFallbackTrackingStates`, we can just use `InputTrackingState`.
- Updating Input.asmdef to correctly define HAS_SET_LOCAL_POSITION_AND_ROTATION

Removing the need for `TDPwithFallbackTrackingStates` and defining HAS_SET_LOCAL_POSITION_AND_ROTATION 

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity

This PR fixes broken HandInteractionExamples scenes:
Previous the PR the scene looks like this :-( :
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/111806d7-120d-48f6-9a02-5be02ef631e4
This PR returns the scene to its proper state with the new controllerless MRTK Rig :-)

XRI3 fix for broken hand interaction examples

---

org.mixedrealitytoolkit.input/Tracking/HandPoseDriver.cs
org.mixedrealitytoolkit.input/Tracking/TrackedPoseDriverExtensions.cs
org.mixedrealitytoolkit.input/Tracking/TrackedPoseDriverExtensions.cs.meta

Adding tracked pose driver extensions. These will help improve "tracking status" queries across interactors.  It also exposes a way for callers to obtain the "cached tracking status" on the HandPoseDriver.

[XRI3] Adding tracked pose driver extensions

---

org.mixedrealitytoolkit.input/Tracking/HandPoseDriver.cs

Fixing HandPoseDrive dispose handling.  The old code failed when running in unit tests, because old object was trying to access the disposed backing-native object.  
NOTE, having to already disposable of this subclass this way is not ideal.  This is code is here as a workaround since the base does not make "OnDisable" virtual.

[XRI3] Fix HandPoseDrive Dispose Handling

---

org.mixedrealitytoolkit.core/Interactors/IModeManagedInteractor.cs
org.mixedrealitytoolkit.input/Interactors/GazePinch/GazePinchInteractor.cs
org.mixedrealitytoolkit.input/Interactors/HandJointInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Poke/PokeInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Ray/MRTKRayInteractor.cs
org.mixedrealitytoolkit.uxcore/Interop/CanvasProxyInteractor.cs

- Updating `IModeManagedInteractor` to use something other than controllers.  
- Also updating interactors to use the new `GetInputTrackingState` extension 
Updating `IModeManagedInteractor` to use something other than controllers.  This is needed for updating `InteractionModeManager` so it does not use controllers either.
NOTE:  Eventually all the MRTK interactors will implement `IModeManagedInteractor`, but this will come in with the changes to `IModeManagedInteractor`

[XRI3] Updating IModeManagedInteractor to use something other than controllers

---

org.mixedrealitytoolkit.input/Visualizers/RiggedHandVisualizer/RiggedHandMeshVisualizer.cs

Updating `RiggedHandMeshVisualizer` so to not rely on deprecated XRI controller components.
This change will require the rig prefab to specify the input reader being used to obtain the selection value for the pinch gesture. Once the controller components are removed from the new rig, I'll update the new rig to hook-up the new `RiggedHandMeshVisualizer`

[XRI3] Updating RiggedHandMeshVisualizer so to not rely on deprecated XRI controller components

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/EyeTracking/EyeTrackingBasicSetupExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/FollowEyeGaze.cs

Updating an eye tracking sample scene so it doesn't use old XRI controllers

[XRI3] Updating eye tracking sample scene so it doesn't use old XRI controllers

---

org.mixedrealitytoolkit.core/Interactors/ITrackedInteractor.cs
org.mixedrealitytoolkit.core/Interactors/ITrackedInteractor.cs.meta
org.mixedrealitytoolkit.input/Interactors/GazePinch/GazePinchInteractor.cs
org.mixedrealitytoolkit.input/Interactors/HandJointInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Poke/PokeInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Ray/MRTKRayInteractor.cs
org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/ObjectManipulator.cs

Updating `ObjectManipulator` so to not rely on obsolete XRI controllers. 
This required introducing a new interactor interface, `ITrackedInteractor`.  This interface provides a way for the `ObjectManipulator` to obtain the transform of the tracked input device.

[XRI3] Updating `ObjectManipulator` so to not rely on obsolete XRI controllers. 

---

org.mixedrealitytoolkit.core/Tests/Runtime/InteractableEventRouterTests.cs

Updating `InteractableEventRouterTests` so it no longer relying on old XRI controllers. This no longer needed, tests pass fine without a need of a controller or an alternative to a controller.

[XRI3] Updating `InteractableEventRouterTests` so it no longer relying on o XRI controllers.

---

org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK Gaze Controller.prefab
org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK XR Rig.prefab
org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTestsForControllerlessRig.cs

…ameObject
* Moving the gaze interactor's TrackedPoseDriver to the parent GameObject so that all controllerless controllers (pun intended ;-) ) have the same structure.  The MRTKGazeController prefab now looks like this with this PR:
* Updated Unity-tests accordingly
* Updated MRTK Rig's Interaction Manager so that it now references the Gaze Controller TrackedPoseDriver and not the GazeInteractor TrackedPoseDriver as in:
Note: Removal of the XRController from the interactors parent and other controllers will be done in a future PR.

XRI3 migration move gaze interactor TrackedPoseDriver to parent GameObject

---

org.mixedrealitytoolkit.input/Experimental/XRI3/HandModel.cs
org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTestsForControllerlessRig.cs

* Updated HandModel to have the same MonoBehavior Awake() as the obsolete XRBaseController.
* Updated BasicInputTestsForControllerlessRig::ControllerlessRigSmokeTest accordingly.

XRI3 migration updating hand model

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity

Fixing HandInteractionExamples scene for 4.0 pre 1 package testing.
The steps to create this PR were:
* Replaced HandInteractionExamples.unity (not the .meta) with the one from MRTK3/main branch.
* Opened the scene and removed the obsolete MRTK rig.
* Added the new MRTK rig to the scene
* Enabled MRTK Speech rig child
* Removed the ghost child under Touch Interaction scene content as shown next:
Update: The ghost child seems to be the broken MRTK_Logo asset as described here: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/848
Additional manual testing for package 4.0 pre 1 testing:
* Modified manifest.json to consume 4.0 pre 1 packages (changed not commited in this PR) as in:
* Created a local build with following scenes:
* Sideloaded build from previous step to …

Fixing HandInteractionExamples scene

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/ObsoleteHandInteractionExamples.unity

Reverting two commits because the error I was seeing were false-positives.  I was seeing those errors because my local git-lfs stopped working but after a reinstall the packages that decode the prefabs I was seeing as missing were properly downloaded and the prefabs are now properly shown.
Additional manual testing of these two reverts:
* Modified manifest.json to consume 4.0 pre 1 packages (changes not committed in this PR) as in:
image
* Generated a local build with the following three scenes:
* Confirmed the three scenes work as expected.

XRI3 migration reverting false positive fixes

---

org.mixedrealitytoolkit.input/Controllers/HandModel.cs

* This aligns with the functionality of the deprecated ArticulatedHandController's ModelPrefab, which allowed runtime setting, that this HandModel is meant to replace.

Allow the HandModel ModelPrefab property to be set at runtime.

---

org.mixedrealitytoolkit.spatialmanipulation/MRTK.SpatialManipulation.asmdef
org.mixedrealitytoolkit.spatialmanipulation/Solvers/HandConstraintPalmUp.cs

The HandMenu was not working in the new controllerless rig.  This is a simple fix to use the GazeTrackedPoseDriver's transform, but also makes use of the TrackedPoseDriver extension TryGetTrackingState(...), which required an assembly reference on Input. 
Does this also mean SpatialManipulation should have a hard dependency on Input in package.manifest?
Solver.cs was already using TrackedPoseDriverLookup, defined in Input, so wouldn't that already cause dependency?

Fix issue with the HandMenu not working in new controllerless rig

---

org.mixedrealitytoolkit.input/InteractionModes/InteractionModeDefinition.cs

Fixes https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/843

Ensure all relevant interactor types show up in InteractionModeManager

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Experimental/SpatialMouseSample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/EyeTracking/EyeTrackingVisualizerExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/SolverExamples.unity

After updating sample scenes to the new XRI3 rig, some interactor references broke on some test behaviours. This change fixes these issues.
Also adjusting a game object name in the "SolverExample" scene, to better example what the game object is.
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/878
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/877
- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/876
Updates scene to use the MRTK3/XRI3 Rig Prefab, this fixed broken interactor references 
Adding hand ray interactor references on the `SolverExampleManager` test behaviour
Adding gaze interactor references on the `LogStructureEyeGaze` test behaviour.

[XRI3] Fixing broken references in sample scenes in XRI3 feature branch.

---

org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/Visuals/SpatialManipulationReticle.cs
org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md

Fixes https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/671
Ensures that we actually pass a `BoundsHandleInteractable` to `RotateReticle`, as that's what it's expecting as far as hierarchy. If we inadvertently pass the `BoundsControl`, the hierarchy logic is incorrect (no parent when it's in the root of the scene).
This case won't be hit in the default MRTK XR Rig. It's only when "Hit Closest Only" on a ray interactor is unchecked that this case is possible.

Fix null ref in SpatialManipulationReticle when multiple interactables are hovered

---

org.mixedrealitytoolkit.input/Controllers/HandModel.cs
org.mixedrealitytoolkit.input/Visualizers/RiggedHandVisualizer/RiggedHandMeshVisualizer.cs

Fixes https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/890
Updates `RiggedHandMeshVisualizer` to treat a non-performed action as a 0 "selectedness".
> [!IMPORTANT]  
>
>I think we may want to consider reverting https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/852 (pinging @whebertML for his thoughts). The default implementation of `XRInputButtonReader` _does_ only return `true` when the action is in progress:
>
>![image](https://github.com/user-attachments/assets/76ccd3f9-cee3-489e-b516-d1f93cc888c6)
>
>I think the underlying issue was that we had at least one code path (the change in this PR) that wasn't properly treating a return value of `false` as equivalent to `0`. Where you seeing the previous return value be problematic in other places …

Fix rigged hand mesh with input actions

---

org.mixedrealitytoolkit.input/Readers/PinchInputReader.cs
org.mixedrealitytoolkit.input/Tracking/TrackedPoseDriverExtensions.cs
org.mixedrealitytoolkit.input/Utilities/InputActionExtensions.cs

Fixes https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/885
Since we were caching the input action availability once on startup, it became impossible to switch between input actions and the polyfill fallback, such as when switching between hands and controllers on a device that doesn't support a hand interaction profile or in an app that doesn't have a hand interaction profile enabled.
This PR updates the input reader logic to check the input action availability once each frame, caching that value for all subsequent uses in the same frame. Since this MonoBehaviour runs at position `k_XRInputDeviceButtonReader = -31000`, it's basically the first thing that runs and it's guaranteed to cache these values before any of it's `Read` methods are called.

Check input action availability every frame instead of once on startup

---

org.mixedrealitytoolkit.audio/CHANGELOG.md
org.mixedrealitytoolkit.audio/package.json
org.mixedrealitytoolkit.extendedassets/CHANGELOG.md
org.mixedrealitytoolkit.extendedassets/package.json
org.mixedrealitytoolkit.tools/CHANGELOG.md
org.mixedrealitytoolkit.tools/package.json
org.mixedrealitytoolkit.uxcomponents.noncanvas/CHANGELOG.md
org.mixedrealitytoolkit.uxcomponents.noncanvas/package.json
org.mixedrealitytoolkit.uxcore/CHANGELOG.md
org.mixedrealitytoolkit.uxcore/package.json

When a package fails to publish to UPM, a new patch release version is required for each subsequent retry.

Update patch versions of packages that failed to publish to UPM

---

Pipelines/rc.yaml

Increase job timeout now that SDL runs in all phases of the RC

Increase job timeout now that SDL runs in all phases of the RC

---

Pipelines/Scripts/update-versions.ps1

(cherry picked from commit b50138a14038ee6fdcce47c13b0c97ed03c0ae57)

Regex update to handle versions without a metatag (#911)

---

org.mixedrealitytoolkit.uxcore/Toggle/ToggleCollection.cs

Minor change: added debug reference to "this" in ToggleCollection.
This permit developer to click on the debug log in the console and Unity focus the component responsible for the warning.
I had this warning but couldn't know from where it was comming (I have multiples ToggleCollection in scene).

Add debug reference to "this" in ToggleCollection

---

org.mixedrealitytoolkit.uxcore/CHANGELOG.md
org.mixedrealitytoolkit.uxcore/StateVisualizer/StateVisualizer.cs
org.mixedrealitytoolkit.uxcore/package.json

StateVisualizer: Add protected access to some internal members to allow subclassing to add new states
resolves #925

StateVisualizer: Add protected access to some internal members to allow subclassing to add new states

---

Pipelines/Templates/1ES/unity.yaml
Pipelines/Templates/docs.yaml
Pipelines/Templates/license-unity.yaml
Pipelines/Templates/unity.yaml
Pipelines/ci.yaml
Pipelines/pr.yaml
Pipelines/rc.yaml

This PR changes the build so we no longer need to checkout the tools.internal repo.  The necessary template to create the unity license config file moves to the pipelines\templates folder in the toolkit repo.

Remove checkout of tools.internal repo

---

Pipelines/Templates/1ES/unity.yaml
Pipelines/Templates/unity.yaml
Pipelines/ci.yaml
Pipelines/pr.yaml
Pipelines/rc.yaml

Changes to the project path were necessary after removing the tools repo checkout.
Tested by running builds on the user/shaynie/testBuild branch.

Update all builds to work without tool repo

---

org.mixedrealitytoolkit.core/CHANGELOG.md
org.mixedrealitytoolkit.core/Editor/Editors/StatefulInteractableEditor.cs
org.mixedrealitytoolkit.core/package.json
org.mixedrealitytoolkit.uxcore/CHANGELOG.md
org.mixedrealitytoolkit.uxcore/Editor/Inspectors/PressableButton/PressableButtonInspector.cs

* Also fixes multi-object modification of "Is Interactable" convenience alias for StatefulInteractable.enabled.
The previous fix to #573 , which was #698, supposedly caused #772.  This should fix both.
Fixes #772
Fixes #573

Fix error message spamming when selecting PressableButtons in Editor

---

UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json

* This updates the com.microsoft.mrtk.graphicstools.unity package to version 0.8.0, which matches the latest version published to the Unity Asset Store at this time.
* This update should fix an issue when opening the project in Unity 6 and using URP.
Fixes #953

Update com.microsoft.mrtk.graphicstools.unity to 0.8.0

---

org.mixedrealitytoolkit.uxcore/Experimental/NonNativeKeyboard/TMPInputFieldNonNativeKeyboardTrigger.cs

Prevents simultaneous editing of multiple input fields when using Non-Native Keyboard
> Test Scene : MRTKDevTemplate/Scenes/Experimental/NonNativeKeyboard
> copying multiple MixedRealityTMPInputField causes an issue where, when multiple Input Fields are clicked, the keyboard ends up editing all of them simultaneously.
>

Prevents simultaneous editing of multiple input fields when using Non-Native Keyboard

---

.gitignore

With Unity 6, I've started seeing this folder generated when creating Android builds. Adding it to the .gitignore.

Update .gitignore to include .utmp folder

---

org.mixedrealitytoolkit.core/Subsystems/Speech/KeywordRecognitionSubsystemDescriptor.cs
org.mixedrealitytoolkit.input/Interactors/Speech/SpeechInteractor.cs
org.mixedrealitytoolkit.windowsspeech/CHANGELOG.md
org.mixedrealitytoolkit.windowsspeech/Subsystems/WindowsKeywordRecognitionSubsystem.cs
org.mixedrealitytoolkit.windowsspeech/package.json

`WindowsKeywordRecognitionSubsystem` now checks itself before attempting registration to ensure it'll run on a supported platform.
Fixes this exception on non-Windows platforms:

Don't register an unsupported Windows speech subsystem

---

UnityProjects/MRTKDevTemplate/Assets/Profiles/MRTKSamplesProfile.asset
UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
org.mixedrealitytoolkit.core/CHANGELOG.md
org.mixedrealitytoolkit.core/Configuration/Default Profiles/MRTKProfile.asset
org.mixedrealitytoolkit.core/Configuration/MRTKProfile.cs
org.mixedrealitytoolkit.core/Editor/MRTKProjectValidation.cs
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/Editor/InputValidation.cs
org.mixedrealitytoolkit.input/Editor/MRTK.Input.Editor.asmdef
org.mixedrealitytoolkit.input/Subsystems/Hands/OpenXRHandsSubsystem.cs

Update MRTK Default Profile to use Unity's XR Hands package

---

org.mixedrealitytoolkit.input/Subsystems/Hands/OpenXRHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/Hands/UnityHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/Hands/XRSDKHandsSubsystem.cs
org.mixedrealitytoolkit.input/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs

Updated the display names to shorten them and make it a bit more clear which API each one supports.
From this:
To this:

Update hands subsystem names for clarity

---

UnityProjects/MRTKDevTemplate/Assets/Scripts/Editor.meta
UnityProjects/MRTKDevTemplate/Assets/Scripts/Editor/AndroidXRConfig.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/Editor/AndroidXRConfig.cs.meta
UnityProjects/MRTKDevTemplate/Assets/XR/XRGeneralSettings.asset

Only affects our in-repo sample project.
Also removes the default ARCore setting as it was interfering, but it's easily re-addable by devs.

Add example config helper for Android XR

---

UnityProjects/MRTKDevTemplate/Assets/XR/XRGeneralSettings.asset
org.mixedrealitytoolkit.input/MRTK.Input.asmdef
org.mixedrealitytoolkit.input/Subsystems/Hands/UnityHandsSubsystem.cs

Permission string and general flow from https://docs.unity3d.com/Packages/com.unity.xr.androidxr-openxr@0.4/manual/get-started/permissions.html
Also uncheck ARCore by default in our project setting for ease of using OpenXR.
Confirmed that on other Android runtimes, this simply auto-returns. Added a note to the log that this is an expected case on some runtimes.

Add hand tracking permission for AndroidXR

---

org.mixedrealitytoolkit.core/Utilities/SerializableDictionary.cs
org.mixedrealitytoolkit.input/Editor/Inspectors/InteractionModeManagerEditor.cs
org.mixedrealitytoolkit.input/InteractionModes/InteractionModeManager.cs

Fixes #958
(in feature/XRI3 branch)
* Also fixes an issue with the "Init Controllers" type lookup within
InteractionModeManager.InitializeControllers() to find XRBaseControllers
instead of XRControllers, since the legacy MRTK controllers derive from
XRBaseControllers, and the GUI button previously wasn't finding any
controller to initialize in the Inspector.

[feature/XRI3] Augment SerializableDictionary to allow temporary duplicates in Editor

---

org.mixedrealitytoolkit.core/Configuration/MRTKProfile.cs
org.mixedrealitytoolkit.core/Editor/MRTKProjectValidation.cs
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/Editor/InputValidation.cs
org.mixedrealitytoolkit.input/Editor/MRTK.Input.Editor.asmdef
org.mixedrealitytoolkit.input/Subsystems/Hands/OpenXRHandsSubsystem.cs

These are relevant in main too!
From #973

 Backport hands subsystem project validation rules from XRI3 branch to main

---

org.mixedrealitytoolkit.core/Subsystems/MRTKLifecycleManager.cs
org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK XR Rig.prefab

We want to ensure we're focused for input, as some runtimes continue reporting "tracked" while pose updates are paused. This is allowed, per-spec, as a "should": "Runtimes should make input actions inactive while the application is unfocused, and applications should react to an inactive input action by skipping rendering of that action's input avatar (depictions of hands or other tracked objects controlled by the user)."

Add new input action focus handling

---

org.mixedrealitytoolkit.core/CHANGELOG.md
org.mixedrealitytoolkit.core/Tests/Runtime/InteractableEventRouterTests.cs
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.uxcomponents/Tests/Runtime/NonNativeKeyboardTests.cs
org.mixedrealitytoolkit.uxcomponents/Tests/Runtime/ScrollableTests.cs
org.mixedrealitytoolkit.uxcore/CHANGELOG.md
org.mixedrealitytoolkit.uxcore/Tests/Runtime/KeyboardPreviewTests.cs
org.mixedrealitytoolkit.uxcore/Tests/Runtime/NonNativeKeyboardTests.cs
org.mixedrealitytoolkit.uxcore/Tests/Runtime/VirtualizedScrollRectListTests.cs

* Updated InteractableEventRouterTests to inherit from BaseRuntimeTests, to use the built-in setup and teardown methods
* Updated other test files to properly override the BaseRuntimeTests setup and teardown methods instead of redefining them
All tests continue to pass:

Update tests to follow existing MRTK test patterns

---

org.mixedrealitytoolkit.input/Assets/Default Configs/MRTKSyntheticHandsConfig.asset
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/Controllers/ArticulatedHandController.cs
org.mixedrealitytoolkit.input/Simulation/Devices/MRTKSimulatedControllerState.cs
org.mixedrealitytoolkit.input/Simulation/Devices/SimulatedController.cs
org.mixedrealitytoolkit.input/Simulation/InputSimulator.cs
org.mixedrealitytoolkit.input/Tests/Runtime/Utilities/InputTestUtilities.cs

* Remaps the synthetic hands config to read the float "select value" action instead of the bool "select" action, since it's read as a float
* Finishes implementing the synthesized `TriggerButton`, accounting for animation smoothing
* Adds a "squeeze" alias for the grip states, to account for broader input action mapping support
All tests continue to pass

Update synthetic hand readings

---

org.mixedrealitytoolkit.core/CHANGELOG.md
org.mixedrealitytoolkit.core/Interactors/IHandedInteractor.cs
org.mixedrealitytoolkit.core/Utilities/Extensions/HandednessExtensions.cs
org.mixedrealitytoolkit.core/Utilities/Extensions/InteractorHandednessExtensions.cs
org.mixedrealitytoolkit.core/Utilities/Extensions/XRNodeExtensions.cs
org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK LeftHand Controller.prefab
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/Controllers/ArticulatedHandController.cs
org.mixedrealitytoolkit.input/InteractionModes/InteractionModeManager.cs
org.mixedrealitytoolkit.input/Interactors/Gaze/GazeInteractor.cs
org.mixedrealitytoolkit.input/Interactors/GazePinch/GazePinchInteractor.cs
org.mixedrealitytoolkit.input/Interactors/HandJointInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Poke/PokeInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Ray/MRTKRayInteractor.cs
org.mixedrealitytoolkit.input/package.json
org.mixedrealitytoolkit.uxcore/CHANGELOG.md
org.mixedrealitytoolkit.uxcore/Interop/CanvasProxyInteractor.cs
org.mixedrealitytoolkit.uxcore/Pulse/InteractablePulse.cs
org.mixedrealitytoolkit.uxcore/package.json

This is now duplicative to `IXRInteractor`'s `handedness`.
Also includes some style and formatting updates across interactors to match the rest of the repo.

Deprecate IHandedInteractor

---

org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK LeftHand Controller.prefab
org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK RightHand Controller.prefab
org.mixedrealitytoolkit.input/CHANGELOG.md
org.mixedrealitytoolkit.input/Controllers/HandModel.cs
org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTests.cs
org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTestsForControllerlessRig.cs

This field was only used for a log, so I'm removing it for simplicity.

Remove HandNode from HandModel

---

org.mixedrealitytoolkit.core/Interactors/IModeManagedInteractor.cs
org.mixedrealitytoolkit.core/Utilities/ControllerLookup.cs
org.mixedrealitytoolkit.input/Controllers/ActionBasedControllerWithFallbacks.cs
org.mixedrealitytoolkit.input/Controllers/ArticulatedHandController.cs
org.mixedrealitytoolkit.input/InteractionModes/FlatScreenModeDetector.cs
org.mixedrealitytoolkit.input/InteractionModes/IInteractionModeDetector.cs
org.mixedrealitytoolkit.input/InteractionModes/InteractionDetector.cs
org.mixedrealitytoolkit.input/InteractionModes/InteractionModeManager.cs
org.mixedrealitytoolkit.input/InteractionModes/ProximityDetector.cs
org.mixedrealitytoolkit.input/Interactors/Gaze/GazeInteractor.cs
org.mixedrealitytoolkit.input/Interactors/GazePinch/GazePinchInteractor.cs
org.mixedrealitytoolkit.input/Interactors/HandJointInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Poke/PokeInteractor.cs
org.mixedrealitytoolkit.input/Interactors/Ray/MRTKRayInteractor.cs
org.mixedrealitytoolkit.input/Utilities/PoseSource/FallbackCompositePoseSource.cs
org.mixedrealitytoolkit.input/Visualizers/RiggedHandVisualizer/RiggedHandMeshVisualizer.cs
org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsHandleInteractable.cs
org.mixedrealitytoolkit.spatialmanipulation/Solvers/Solver.cs
org.mixedrealitytoolkit.uxcore/Interop/CanvasProxyInteractor.cs

Updates the new `Obsolete` messages to clarify the version it was deprecated in.
Also removes some stale `Obsolete` code paths from 3.x.

Clarify newly obsolete code due to XRI3 refactor

---

org.mixedrealitytoolkit.input/Tests/Runtime/Utilities/TestHand.cs
org.mixedrealitytoolkit.uxcomponents.noncanvas/Tests/Runtime/SliderTests.cs
org.mixedrealitytoolkit.uxcomponents/Tests/Runtime/SliderTests.cs

* Uncomments (but ignores) a few stale tests to ensure they don't get completely forgotten
* Updates some slider tests to align on the handles instead of some parent prefab
* Ensures we `SetHandAnchorPoint` for each test depending on if it's for touch or grab

Ensure consistency on slider tests
