MixedRealityToolkit/MixedRealityToolkit-Unity

UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset
(cherry picked from commit fccca4d2b69db204b2413cb2b9b13d040bd06183)
=> Cherrypick: for template project, use organization name

CODEOWNERS
ensure that the maintainers are listed as owners on all of the packages and the sample project
=> add maintainers group to each package

contributions/versioning-and-releases.md
Fixing link to MRTK releases page
The link was pointing an invalid location.
=> Fixing link to MRTK releases page

UnityProjects/MRTKDevTemplate/Assets/Scenes/DisableInteractorsExample.unity, org.mixedrealitytoolkit.uxcore/Slider/Slider.cs
Switching the math around so that non-normalized value is passed into SnapSliderToStepPosition.
=> Fix Slider Snapped Step Positions with Non-Default Range

org.mixedrealitytoolkit.core/package.json
=> Update Core Patch Version

contributions/opening-and-assessing-issues.md, org.mixedrealitytoolkit.uxcore/Slider/Slider.cs
Publicly documenting how critical issues are handled by Project Maintainers.
- Fixes: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/466
=> Adding guidance for addressing critical issues

org.mixedrealitytoolkit.uxcomponents/Editor/CreateElementMenus.cs
* Fixes MRTK UI menu commands not working when there is no main camera
* Also places created objects in the current stage (main stage vs prefab stage).
Fixes:  #520
=> Fixing MRTK UI menu commands not working when there is no main camera

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
If you open the current dev template in unity it will generate the modified package-lock.json file
=> Update MRTKDevTemplate packages-lock.json for 3.1.0

org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsHandleInteractable.cs
=> Fix unessessary allocation (#570)

org.mixedrealitytoolkit.core/Interactables/StatefulInteractable.cs, org.mixedrealitytoolkit.uxcomponents.noncanvas/Tests/Runtime/PressableButtonTests.cs
Fixes #591 
+ Fix the warning and wrong event triggered
+ Add non-regression tests
+ Make VoiceRequiresFocus public
=> Fix warning and event triggered on disabled StatefulInteractable after changing speech settings (#591)

org.mixedrealitytoolkit.input/Visualizers/ControllerVisualizer/Models/generic-trigger-squeeze-touchpad-thumbstick/LeftControllerModel.prefab, org.mixedrealitytoolkit.input/Visualizers/ControllerVisualizer/Models/generic-trigger-squeeze-touchpad-thumbstick/RightControllerModel.prefab
#559 introduced a regression where the controller models' rotational offset wasn't properly committed to the PR. This PR fixes that.
=> Fix the fallback controllers being backwards

org.mixedrealitytoolkit.accessibility/AssemblyInfo.cs, org.mixedrealitytoolkit.audio/AssemblyInfo.cs, org.mixedrealitytoolkit.core/AssemblyInfo.cs, org.mixedrealitytoolkit.data/AssemblyInfo.cs, org.mixedrealitytoolkit.diagnostics/AssemblyInfo.cs, org.mixedrealitytoolkit.input/AssemblyInfo.cs, org.mixedrealitytoolkit.spatialmanipulation/AssemblyInfo.cs, org.mixedrealitytoolkit.tools/AssemblyInfo.cs, org.mixedrealitytoolkit.uxcomponents.noncanvas/AssemblyInfo.cs, org.mixedrealitytoolkit.uxcomponents/AssemblyInfo.cs, org.mixedrealitytoolkit.uxcore/AssemblyInfo.cs, org.mixedrealitytoolkit.windowsspeech/AssemblyInfo.cs
Manually update versions in  AssemblyInfo files for the release branch.  This is a manual fix for generating the docs.
=> Manually update versions in  AssemblyInfo files for the release branch

org.mixedrealitytoolkit.uxcore/Slider/Visuals/SliderVisuals.cs
=> fix for erroneous scaling of slider visual

MAINTAINERS.md
Added Max Palmer and Rob Blenkinsopp to the maintainers list (from Ultraleap).
=> Added Max Palmer and Rob Blenkinsopp to the maintainers list

org.mixedrealitytoolkit.accessibility/CHANGELOG.md, org.mixedrealitytoolkit.accessibility/package.json, org.mixedrealitytoolkit.audio/CHANGELOG.md, org.mixedrealitytoolkit.core/CHANGELOG.md, org.mixedrealitytoolkit.data/CHANGELOG.md, org.mixedrealitytoolkit.data/package.json, org.mixedrealitytoolkit.diagnostics/CHANGELOG.md, org.mixedrealitytoolkit.extendedassets/CHANGELOG.md, org.mixedrealitytoolkit.extendedassets/package.json, org.mixedrealitytoolkit.input/CHANGELOG.md, org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md, org.mixedrealitytoolkit.standardassets/CHANGELOG.md, org.mixedrealitytoolkit.tools/CHANGELOG.md, org.mixedrealitytoolkit.uxcomponents.noncanvas/CHANGELOG.md, org.mixedrealitytoolkit.uxcomponents/CHANGELOG.md, org.mixedrealitytoolkit.uxcore/CHANGELOG.md, org.mixedrealitytoolkit.windowsspeech/CHANGELOG.md
Update CHANGELOG dates and notes before branching for release
=> Update changelogs and package.json files to prep release

org.mixedrealitytoolkit.standardassets/Fonts/Selawik-Bold-MRTKIcons SDF.asset, org.mixedrealitytoolkit.standardassets/Fonts/Selawik-Light-MRTKIcons SDF.asset, org.mixedrealitytoolkit.standardassets/Fonts/Selawik-Regular-MRTKIcons SDF.asset, org.mixedrealitytoolkit.standardassets/Fonts/Selawik-Semibold-MRTKIcons SDF.asset, org.mixedrealitytoolkit.standardassets/Fonts/Selawik-Semilight-MRTKIcons SDF.asset
Making Selawik* atlas' textures readable for fixing bug https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/713
=> Making Selawik* atlas' textures readable

org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControl.cs, org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md, org.mixedrealitytoolkit.spatialmanipulation/package.json
Made four functions in boundscontrol.cs protected virtual and updated changelog and package.json accordingly.
This is necessary for adding custom translation, rotation and scaling logic for bound controls behavior.
=> Made Bound Controls Overridable And Updated Changelog

org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControlMoveLogic.cs, org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControlRotateLogic.cs, org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControlScaleLogic.cs
[Bug 725 - Missing copyright statements](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/725)
=> Fix for Bug725 Missing copyright notification

org.mixedrealitytoolkit.core/CHANGELOG.md, org.mixedrealitytoolkit.core/Editor/Editors/BaseInteractableEditor.cs, org.mixedrealitytoolkit.core/Editor/Editors/MRTKProfileEditor.cs, org.mixedrealitytoolkit.core/Editor/Editors/MRTKSettingsEditor.cs, org.mixedrealitytoolkit.data/CHANGELOG.md, org.mixedrealitytoolkit.data/Editor/Inspectors/DataConsumerSpriteInspector.cs, org.mixedrealitytoolkit.data/Editor/Inspectors/DataKeyPathMapperInspector.cs, org.mixedrealitytoolkit.input/CHANGELOG.md, org.mixedrealitytoolkit.input/Editor/Inspectors/InteractionDetectorEditor.cs, org.mixedrealitytoolkit.input/Editor/Inspectors/InteractionModeManagerEditor.cs, org.mixedrealitytoolkit.input/Editor/Inspectors/UnboundedTrackingModeInspector.cs, org.mixedrealitytoolkit.uxcore/CHANGELOG.md, org.mixedrealitytoolkit.uxcore/Editor/Inspectors/FontIconSet/FontIconSelectorInspector.cs, org.mixedrealitytoolkit.uxcore/Editor/Inspectors/FontIconSet/FontIconSetInspector.cs, org.mixedrealitytoolkit.uxcore/Editor/Inspectors/PressableButton/PressableButtonInspector.cs, org.mixedrealitytoolkit.uxcore/Editor/Inspectors/Slider/SliderInspector.cs
This is for https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/573
=> Adding missing [CanEditMultipleObject] attributes

org.mixedrealitytoolkit.uxcomponents/Button/Prefabs/PressableButton_Custom_Cylinder.prefab, org.mixedrealitytoolkit.uxcomponents/CHANGELOG.md
=> Fix PressableButton_Custom_Cylinder Tube object using default material.

org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTests.cs, org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTestsForControllerlessRig.cs, org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTestsForControllerlessRig.cs.meta, org.mixedrealitytoolkit.input/Tests/Runtime/InteractionModeManagerTests.cs, org.mixedrealitytoolkit.input/Utilities/InputTrackingStateExtensions.cs, org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControl.cs, org.mixedrealitytoolkit.uxcore/Button/PressableButton.cs
* Added XRI3+ versions of BasicInputTests InputBindingSmoketest, HandMovingSmoketest, InteractableDisabledDuringInteraction, SpawnInteratableOnHand, and UntrackedHandNearInteractions.
=> XRI3 migration step09

org.mixedrealitytoolkit.input/Assets/Prefabs/Experimental-XRI3/MRTK XR Rig.prefab, org.mixedrealitytoolkit.input/Tests/Runtime/FuzzyGazeInteractorTestsForControllerlessRig.cs, org.mixedrealitytoolkit.input/Tests/Runtime/FuzzyGazeInteractorTestsForControllerlessRig.cs.meta
* Added XRI3+ versions of FuzzyGazeInteractorTests.
* Fixing some input action references in MRTK XRI3+ rig.
=> XRI3 migration step13

org.mixedrealitytoolkit.input/Interactors/GazePinch/GazePinchInteractor.cs, org.mixedrealitytoolkit.input/Interactors/Poke/PokeInteractor.cs, org.mixedrealitytoolkit.input/Interactors/Ray/MRTKRayInteractor.cs, org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTestsForControllerlessRig.cs, org.mixedrealitytoolkit.input/Tests/Runtime/Utilities/InputTestUtilities.cs
* Adding ControllerlessRigSmokeTest
* Making some interactor properties public so that they can be tested.
* Added InputTestUtilities.RigReference to facilitate testing.
=> XRI3 migration step14

Pipelines/rc.yaml, UnityProjects/MRTKDevTemplate/ProjectSettings/EditorBuildSettings.asset, org.mixedrealitytoolkit.core/CHANGELOG.md, org.mixedrealitytoolkit.core/Tests/TestUtilities/PackageValidatorResults.cs, org.mixedrealitytoolkit.input/CHANGELOG.md, org.mixedrealitytoolkit.input/Editor/Inspectors/EyeGazeSimulationSettingsDrawer.cs, org.mixedrealitytoolkit.input/Simulation/Devices/SimulatedController.cs, org.mixedrealitytoolkit.input/Simulation/InputSimulator.cs, org.mixedrealitytoolkit.uxcomponents/Button/Prefabs/PressableButton_Custom_Cylinder.prefab, org.mixedrealitytoolkit.uxcomponents/CHANGELOG.md, org.mixedrealitytoolkit.uxcore/StateVisualizer/StateVisualizer.cs, org.mixedrealitytoolkit.uxcore/Tests/Runtime/StateVisualizerTests.cs
Merging `main` into `feature\XRI3`
=> Merging `main` into `feature\XRI3`

org.mixedrealitytoolkit.input/CHANGELOG.md, org.mixedrealitytoolkit.standardassets/CHANGELOG.md
The data format was incorrect in one file, and the other file was missing a header.
=> Fixing some change log format bugs

org.mixedrealitytoolkit.input/CHANGELOG.md, org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTestsForControllerlessRig.cs, org.mixedrealitytoolkit.input/Tests/Runtime/FuzzyGazeInteractorTestsForControllerlessRig.cs, org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md, org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverHandlerTestsForControllerlessRig.cs
…ss prefabs
* Ported remaining MixedReality.Toolkit.Input.Tests.BasicInputTests so that they test the new controllerless prefabs too.
* Ported remaining MixedReality.Toolkit.Input.Tests.FuzzyGazeInteractorTests so that they test the new controllerless prefabs too.
* Ported remaining MixedReality.Toolkit.Input.Tests.SolverTapToPlaceTests so that they test the new controllerless prefabs too.
* Updated changelogs accordingly.
=> XRI3 migration porting remaining tests for controllerless prefabs

org.mixedrealitytoolkit.input/Interactors/HandJointInteractor.cs, org.mixedrealitytoolkit.input/Interactors/Ray/MRTKRayInteractor.cs
- Updating MRTKRayInteractor so it doesn't rely on obsolete XRI controllers
=> [XRI3] Updating MRTKRayInteractor so it doesn't rely on obsolete XRI controllers

org.mixedrealitytoolkit.core/CHANGELOG.md, org.mixedrealitytoolkit.input/CHANGELOG.md, org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md, org.mixedrealitytoolkit.uxcomponents.noncanvas/CHANGELOG.md, org.mixedrealitytoolkit.uxcomponents/CHANGELOG.md, org.mixedrealitytoolkit.uxcore/CHANGELOG.md
* Updating CHANGELOG.md files to reflect latest PRs merged to feature/XRI3
=> XRI3 migration change logs review

Pipelines/rc.yaml
Dup of https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/834
=> Fix RC pipeline serviceconnection

Pipelines/rc.yaml
=> Fix RC pipeline serviceconnection (#835)

org.mixedrealitytoolkit.input/Assets/Input Actions/MRTK Default Input Actions.inputactions
Adding "<XRController>{LeftHand}/squeeze" and "<XRController>{RightHand}/squeeze" action mappigns for MRTK3's "selectValue" action
=> Adding hand "squeeze" binding for MRTK3's "selectValue" action (#858)

org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK LeftHand Controller.prefab, org.mixedrealitytoolkit.input/Controllers/ArticulatedHandController.cs, org.mixedrealitytoolkit.input/Readers/PinchInputReader.cs, org.mixedrealitytoolkit.input/Tests/Runtime/FuzzyGazeInteractorTestsForControllerlessRig.cs, org.mixedrealitytoolkit.input/Tracking/HandPoseDriver.cs, org.mixedrealitytoolkit.input/Tracking/TrackedPoseDriverExtensions.cs, org.mixedrealitytoolkit.input/Tracking/TrackedPoseDriverWithFallback.cs, org.mixedrealitytoolkit.input/Utilities/PoseSource/InputActionPoseSource.cs, org.mixedrealitytoolkit.spatialmanipulation/Solvers/HandConstraintPalmUp.cs
Cherry pick PR #864 and #862 into MRTK3 preview release branch
#864
#862
=> cherry pick PR #864 and #862 into MRTK3 preview release branch

org.mixedrealitytoolkit.input/CHANGELOG.md
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/872
Oops...
=> Update CHANGELOG.md for #872

org.mixedrealitytoolkit.core/Editor/EditorProjectUtilities.cs, org.mixedrealitytoolkit.core/Utilities/Extensions/TransformExtensions.cs, org.mixedrealitytoolkit.data/Runtime/Scripts/DataSources/DataSourceGOJson.cs, org.mixedrealitytoolkit.input/Interactors/InteractorVisuals/Lines/DataProviders/BaseMixedRealityLineDataProvider.cs, org.mixedrealitytoolkit.input/Interactors/Speech/SpeechInteractor.cs, org.mixedrealitytoolkit.input/Tests/Runtime/BasicInputTests.cs, org.mixedrealitytoolkit.input/Tracking/UnboundedTrackingMode.cs, org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverHandlerTests.cs, org.mixedrealitytoolkit.uxcomponents/Tests/Runtime/NonNativeKeyboardTests.cs, org.mixedrealitytoolkit.uxcore/Experimental/List/Scrollable.cs, org.mixedrealitytoolkit.uxcore/Experimental/NonNativeKeyboard/NonNativeKeyboard.cs, org.mixedrealitytoolkit.uxcore/Keyboard/KeyboardPreview.cs, org.mixedrealitytoolkit.uxcore/Slider/SliderSounds.cs
I've had some minor changes I've been carrying around for a little bit now, so I figure I should go ahead and get them reviewed.
1. Use more `TryGetComponent`
2. Inline some `out` params
3. Simplify some syntax (`?.`) and logic, where possible
4. Remove some unused local fields
=> Assorted cleanliness updates

Pipelines/rc.yaml
(cherry picked from commit 868635d014b5fb9f07c5c93bbdc4ec459948eadb)
=> Increase job timeout now that SDL runs in all phases of the RC (#908)

Pipelines/Templates/1ES/unity.yaml, Pipelines/Templates/docs.yaml, Pipelines/Templates/license-unity.yaml, Pipelines/Templates/unity.yaml, Pipelines/ci.yaml, Pipelines/pr.yaml, Pipelines/rc.yaml
Pull build changes from main into feature/XRI3 to allow builds to complete.
=> Cherrypick build changes from main

org.mixedrealitytoolkit.core/CHANGELOG.md, org.mixedrealitytoolkit.core/Editor/Editors/StatefulInteractableEditor.cs, org.mixedrealitytoolkit.uxcore/CHANGELOG.md, org.mixedrealitytoolkit.uxcore/Editor/Inspectors/PressableButton/PressableButtonInspector.cs
…(#943)
* Also fixes multi-object modification of "Is Interactable" convenience alias for StatefulInteractable.enabled.
(cherry picked from commit 3351ba1acb3a039bec9ac4c15de67fb2bbbb29f8)
=> Cherry-pick #943 from main to feature/XRI3

UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/TargetPositioning/MoveObjectByEyeGaze.cs, UnityProjects/MRTKDevTemplate/Assets/Scripts/TetheredPlacement.cs, org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md, org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/ObjectManipulator.cs, org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/ObjectManipulatorTests.cs, org.mixedrealitytoolkit.spatialmanipulation/package.json
=> Update script compatibility with Unity6 changes to Rigidbody properties

org.mixedrealitytoolkit.spatialmanipulation/ObjectManipulator/MoveLogics/ScaleLogic.cs
=> Fix issue in ScaleLogic when multiple interactors have same position

org.mixedrealitytoolkit.input/InteractionModes/InteractionModeManager.cs
=> Fix destroyed interactor group cleanup logic in InteractionModeManager.Update()

GOVERNANCE.md, MAINTAINERS.md
=> Merge main into feature/XRI3

org.mixedrealitytoolkit.spatialmanipulation/Tests/Runtime/SolverHandlerTestsForControllerlessRig.cs
Found this in a stray branch locally 🙃
=> Minor syntax update to XRI3 test

org.mixedrealitytoolkit.core/Utilities/Extensions/ComponentExtensions.cs, org.mixedrealitytoolkit.uxcore/Slider/SliderSounds.cs
- Unsubscribe SliderSounds from Slider event when disabled
- Updated utility function EnsureComponent to use TryGetComponent
=> Fix SliderSounds playing sound even when disabled (#1006)

org.mixedrealitytoolkit.core/Subsystems/Speech/DictationSubsystemDescriptor.cs, org.mixedrealitytoolkit.windowsspeech/CHANGELOG.md, org.mixedrealitytoolkit.windowsspeech/Subsystems/WindowsDictationSubsystem.cs
Follow-up to https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/978
=> Don't register dictation subsystem on non-Windows

UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
=> [Samples] Add a button to reopen the whiteboard after closing

org.mixedrealitytoolkit.core/CHANGELOG.md, org.mixedrealitytoolkit.uxcore/CHANGELOG.md
From https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/961 and https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/1007
=> Add some missing changelogs

UnityProjects/MRTKDevTemplate/ProjectSettings/MixedRealityOpenXRValidationSettings.asset, UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset
=> Turn off run in background in sample project to match MR OpenXR Plugin recommendation

UnityProjects/MRTKDevTemplate/Assets/Editor/MeasureToolSettings.asset, UnityProjects/MRTKDevTemplate/Assets/Editor/MeasureToolSettings.asset.meta
This file keeps being generated by MRGT, so we may as well check it in.
=> Add MeasureToolSettings.asset from MRGT

org.mixedrealitytoolkit.core/Subsystems/MRTKLifecycleManager.cs, org.mixedrealitytoolkit.input/Assets/Prefabs/MRTK XR Rig.prefab
This reverts commit f52cdedaa3dbf8b272851a3c2f63f67ae8d743c4.
I'm gonna add this to the XRI3 branch _only_.
=> Revert "Add new input action focus handling (#1028)" in main

org.mixedrealitytoolkit.input/Subsystems/Hands/UnityHandsSubsystem.cs
Doesn't appear to be necessary off-device.
=> Don't ask for the Android XR hand permission in-editor
